# config.yaml

MAF: 0.01
GENO: 0.1
HWE: "1e-10"
MAC: 5
Ancestry: ['black', 'asian', 'mixed', 'chinese']
CHR: ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22']
plink_executable: "/data2/morgante_lab/kgoda/software/plink1.9/plink"
out_dir: "/data2/morgante_lab/ukbiobank_projects/GxE_multi_ancestry/output"
geno_dir: "/data2/morgante_lab/data/ukbiobank/genotypes/array"
sample_ids_dir: "/data2/morgante_lab/ukbiobank_projects/GxE_multi_ancestry/data"
snp_list_dir: "/data2/morgante_lab/ukbiobank_projects/GxE_multi_ancestry/output/snp_lists"
EXT: ".bed"