resources: [cpus=400, mem_mb=8000000, jobweight=40, solo=1]

cluster:
  mkdir -p /data2/morgante_lab/ukbiobank_projects/GxE_mapping/logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --ntasks-per-core={resources.ntpc}
    --ntasks={resources.tasks}
    --cpus-per-task={threads}
    --mem-per-cpu={resources.mem_mb_per_cpu}
    --job-name={rule}
    --output=/data2/morgante_lab/ukbiobank_projects/GxE_mapping/logs/{rule}/%jo_{rule}_{wildcards}
    --error=/data2/morgante_lab/ukbiobank_projects/GxE_mapping/logs/{rule}/%je
    --time={resources.time_min}

default-resources:
  - partition='fm-bigmem-1,fm-bigmem-2,fm-bigmem-3,fm-bigmem-4'
# - partition='fm-bigmem-1,fm-bigmem-3,fm-bigmem-4'
# - partition='fm-bigmem-1'
# - partition='fm-bigmem-2'
# - partition='fm-bigmem-3'
  # - partition='fm-bigmem-4'
# - partition='compute'
# - partition='bigmem'
  - mem_mb_per_cpu=12000
  - time_min="4-00:00:00"
  - nodes=4
  - tasks=1
  - ntpc=1
  - mem_mb=10000
# - mem_mb=2
# - time_min=1440

latency-wait: 20
local-cores: 1
keep-going: True
keep-incomplete: True
rerun-incomplete: True
rerun-triggers: 'mtime'
nolock: True
printshellcmds: True
use-conda: True
conda-frontend: 'mamba'
